# Generated by Django 2.0 on 2020-06-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default='', upload_to='media/', verbose_name='file')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mails.Mail')),
            ],
        ),
    ]
